version: '3.7'

services:
  keycloakdb:
    image: postgres
    ports:
      - '50640:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '3255:8080'
    command:
      - start-dev
    depends_on:
      - keycloakdb

  recipemanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '50604:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=MELNe1378valya202520252025!*$
      - DB_CONTAINER_NAME=dev_recipemanagement
      - ACCEPT_EULA=Y
    volumes:
      - recipemanagement-data:/var/lib/sqlserver/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "50614:5775/udp"
      - "50613:6831/udp"
      - "50615:6832/udp"
      - "50616:5778"
      - "50617:16686"
      - "50618:14250"
      - "50619:14268"
      - "50620:14269"
      - "50621:9411"

        
volumes:
  # compose volumes marker - do not delete
  keycloak-data:
  recipemanagement-data:
